-- Maintenance Desk redesign, on the shared repair tickets table. Run once in
-- the Supabase SQL Editor of the Duty Desk project (the one project that now
-- holds all three departments), AFTER 0007. Then run
-- apps/maintenance-desk/supabase/migrations/0003_suite_redesign.sql.
-- Safe to re-run. It only adds things; nothing existing is changed.

-- Who did the work and when, so Duty Desk sees who started a job, who fixed
-- it, at what time and what was done.
alter table maintenance_tickets
  add column if not exists started_by_name text,
  add column if not exists started_at timestamptz,
  add column if not exists resolved_by_name text,
  add column if not exists resolved_at timestamptz,
  add column if not exists fix_note text;

-- Requests: work asked for outside Duty Desk (the maintenance team itself,
-- the CEO, COO, managers, Security, other departments). They're tickets with
-- source = 'request', shown on Maintenance Desk's Requests page and never in
-- Duty Desk. These say who asked.
alter table maintenance_tickets
  add column if not exists requested_by_name text,
  add column if not exists requested_by_role text,
  add column if not exists requested_by_unit text;

create index if not exists maintenance_tickets_source_idx on maintenance_tickets (source);

-- A short number people can say and write on vouchers: MT-0042. Existing
-- tickets are numbered when this runs.
alter table maintenance_tickets
  add column if not exists ref_no bigint generated by default as identity;

-- assigned_to now holds one of the five maintenance units (General
-- Maintenance, Electrician, Plumbing & Building, Painting, Welding) or
-- Housekeeping. Older tickets may still say "Engineering"; Maintenance Desk
-- shows those as needing a unit, and the Manager or Supervisor picks one.

notify pgrst, 'reload schema';
