-- Gatehouse redesign (Operations Suite). Run once in the Supabase SQL Editor
-- of the one project that holds all three departments; Gatehouse's tables
-- live in its "gatehouse" schema there. Safe to re-run. It only adds things;
-- nothing existing is changed.

-- Alerts: after someone acknowledges an alert it stays on every Gatehouse
-- screen until it's resolved with notes (what happened, the all-clear).
alter type gatehouse.gh_alert_status add value if not exists 'Resolved';
alter table gatehouse.alerts
  add column if not exists resolution_notes text,
  add column if not exists resolved_by uuid references gatehouse.staff_accounts(id),
  add column if not exists resolved_at timestamptz;

-- Incidents: who resolved it and when (the resolution notes column already
-- exists), and a short number people can say and write: INC-0042. Existing
-- incidents are numbered oldest first; new ones carry on from there.
alter table gatehouse.incidents
  add column if not exists resolved_by uuid references gatehouse.staff_accounts(id),
  add column if not exists resolved_at timestamptz;
do $$
begin
  if not exists (select 1 from information_schema.columns
                 where table_schema = 'gatehouse' and table_name = 'incidents' and column_name = 'ref_no') then
    alter table gatehouse.incidents add column ref_no bigint;
    update gatehouse.incidents t set ref_no = n.rn
      from (select id, row_number() over (order by created_at, id) as rn from gatehouse.incidents) n
      where t.id = n.id;
    alter table gatehouse.incidents alter column ref_no set not null;
    alter table gatehouse.incidents alter column ref_no add generated by default as identity;
    perform setval(pg_get_serial_sequence('gatehouse.incidents', 'ref_no'),
                   coalesce((select max(ref_no) from gatehouse.incidents), 0) + 1, false);
  end if;
end $$;
create unique index if not exists incidents_ref_no_idx on gatehouse.incidents (ref_no);

-- Settings the Admin can change. rack_size: how many vehicle cards the gate
-- hands out (numbered 001 up); the Gate Console shows them as a rack.
create table if not exists gatehouse.settings (
  key text primary key,
  value text not null,
  updated_by_name text,
  updated_at timestamptz not null default now()
);
insert into gatehouse.settings (key, value) values ('rack_size', '60') on conflict (key) do nothing;
alter table gatehouse.settings enable row level security;
grant all on gatehouse.settings to service_role;

-- Who logged a vehicle out and who booked an item back in (entries already
-- record who logged them), so every step at the gate is signed.
alter table gatehouse.vehicle_logs
  add column if not exists exit_logged_by uuid references gatehouse.staff_accounts(id);
alter table gatehouse.item_logs
  add column if not exists in_logged_by uuid references gatehouse.staff_accounts(id);

-- The Gate Console looks up the cards that are out on every entry.
create index if not exists vehicle_logs_status_idx on gatehouse.vehicle_logs (status);

notify pgrst, 'reload schema';
